AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'simple-state-machine

  Sample SAM Template for simple-state-machine

  '
Resources:
  kijijiApartment:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state-machine/state.json
      DefinitionSubstitutions:
        fetchResultsArn: !GetAtt fetchApartmentsFunction.Arn
        validateApartmentArn: !GetAtt validateApartmentsFunction.Arn
        sendEmailArn: !GetAtt  sendEmailFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: "apartment"
      Events:
        HourlyTradingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: false
            Schedule: rate(1 hour)
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: fetchApartmentsFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: validateApartmentsFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: sendEmailFunction
  fetchApartmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/fetchApartments
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 120
      Policies:
        - DynamoDBWritePolicy:
            TableName:
              Ref: apartment
  validateApartmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/filterapartments
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 120
  sendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/sendEmail
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 30
      Policies:
        - SESCrudPolicy:
            IdentityName: Kapooky101@gmail.com

  apartment:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: apartment
      PrimaryKey:
        Name: apartmentUrl
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  StockTradingStateMachineArn:
    Description: Stock Trading state machine ARN
    Value:
      Ref: kijijiApartment
